#!/usr/bin/python3
import pygame;

surface = pygame.display.set_mode([340,200]);
pygame.display.flip();
def draw(sx,sy,x,y):
    pygame.draw.rect(surface, (255,255,255), (sx,sy,x,y));
def drawb(sx,sy,x,y):
    pygame.draw.rect(surface, (0,0,0), (sx,sy,x,y));
def h(sx,sy,ssx,ssy,sssx,sssy):
    draw(sx,sy, 1,5);
    draw(ssx,ssy, 1,5);
    draw(sssx,sssy, 5,1);
def i(sx,sy):
    draw(sx,sy, 1,5);
def n1(sx,sy,ssx,ssy,sssx,sssy):
    draw(sx,sy, 1,1);
    draw(ssx,ssy, 1,1);
    draw(sssx,sssy, 1,5);
def n0(sx,sy,ssx,ssy,sssx,sssy,ssssx,ssssy):
    draw(sx,sy,3,1);
    draw(ssx,ssy,1,4);
    draw(sssx,sssy,4,1);
    draw(ssssx,ssssy,1,4);
def a(sx,sy,ssx,ssy,sssx,sssy,ssssx,ssssy):
    draw(sx,sy,1,5);
    draw(ssx,ssy,4,1);
    draw(sssx,sssy,1,5);
    draw(ssssx,ssssy,4,1);
def b(sx,sy,ssx,ssy,sssx,sssy,ssssx,ssssy,sssssx,sssssy):
    draw(sx,sy,1,4);
    draw(ssx,ssy,4,1);
    draw(sssx,sssy,1,3);
    draw(ssssx,ssssy,4,1);
    draw(sssssx,sssssy,4,1);
def c(sx,sy,ssx,ssy,sssx,sssy):
    draw(sx,sy,1,4);
    draw(ssx,ssy,4,1);
    draw(sssx,sssy,4,1);
def d(sx,sy,ssx,ssy,sssx,sssy,ssssx,ssssy):
    draw(sx,sy,1,4);
    draw(ssx,ssy,4,1);
    draw(sssx,sssy,1,3);
    draw(ssssx,ssssy,4,1);
def e(sx,sy,ssx,ssy,sssx,sssy,ssssx,ssssy):
    draw(sx,sy,1,4);
    draw(ssx,ssy,4,1);
    draw(sssx,sssy,4,1);
    draw(ssssx,ssssy,4,1);
def f(sx,sy,ssx,ssy,sssx,sssy):
    draw(sx,sy,1,5);
    draw(ssx,ssy,4,1);
    draw(sssx,sssy,4,1);
def g(sx,sy,ssx,ssy,sssx,sssy,ssssx,ssssy,sssssx,sssssy):
    draw(sssssx,sssssy,5,1);
    draw(sx,sy,1,5);
    draw(ssx,ssy,4,1);
    draw(sssx,sssy,1,3);
    draw(ssssx,ssssy,3,1);
def j(sx,sy,ssx,ssy):
    draw(sx,sy,1,4);
    draw(ssx,ssy,4,1);
def k(sx,sy,ssx,ssy,sssx,sssy,ssssx,ssssy,sssssx,sssssy,ssssssx,ssssssy,sssssssx,sssssssy):
    draw(sx,sy,1,5);
    draw(ssx,ssy,2,1);
    draw(sssx,sssy,1,1);
    draw(ssssx,ssssy,2,1);
    draw(sssssx,sssssy,2,1);
    draw(ssssssx,ssssssy,1,1);
    draw(sssssssx,sssssssy,2,1);
def l(sx,sy,ssx,ssy):
    draw(sx,sy,1,5);
    draw(ssx,ssy,4,1);
n0(0,0, 0,0, 0,4, 3,0);
n1(5,2, 6,1, 7,0);
a(9,0, 9,0, 13,0, 9,2);
b(15,0, 15,0, 19,1, 15,4, 15,2);
c(21,0, 21,0, 21,4);
d(26,0, 26,0, 30,1, 26,4);
e(32,0, 32,0, 32,2, 32,4);
f(37,0, 37,0, 37,2);
g(42,0, 42,4, 46,2, 44,2, 42,0);
h(48,0, 52,0, 48,2);
i(54,0);
j(60,0, 56,4);
k(62,0, 62,1, 64,1, 64,0, 62,3, 64,3, 64,4);
l(67,0, 67,4);
pygame.display.update();
while True:
    pass;
